= relex-id

Semantic dependency relationship extractor untuk bahasa Indonesia (termasuk bahasa gaul dan alay ;))

Optional: mendukung ekstraksi dari bahasa Indonesia ke struktur sentence RelEx (English).

== Dictionary

=== Noun

----
i(first, singular) 'aku', saya'
you(second, singular) 'kamu', 'Anda'
he(third, singular) 'dia', 'ia'
she(third, singular) 'dia', 'ia'
we_sm(first, plural) 'kami'
we_lg(first, plural) 'kita'
you_plural(second, plural) 'kalian'
they(third, plural) 'mereka'
----

=== Verb

(belum memakai stemming)

----
see 'lihat', 'melihat', 'pandang', 'memandang'
----

=== Kata Hubung

1. `at`: di

=== Question

----
what 'apa'
----

Question variable extraction digunakan untuk mendapatkan variabel apa yang ditanyakan.

== RDF Dataset

=== Namespaces

----
@prefix dbpedia-owl:	<http://dbpedia.org/ontology/> .
@prefix dbpedia:		<http://dbpedia.org/resource/> .
@prefix schema:			<http://schema.org> .
@prefix wn30:			<http://purl.org/vocabularies/princeton/wn30/> .
----

=== Animal

----
dbpedia-owl:Animal 'binatang', 'hewan'
----

Semua resources di sini diasumsikan `a dbpedia-owl:Animal`. 

----
dbpedia:Elephant 'gajah'
----

=== Place

Semua resources di sini diasumsikan `a http://schema.org/Place`.

----
dbpedia:Zoo 'kebun binatang'
----

== Format

Aku melihat binatang gajah di kebun binatang.

    noun verb 'binatang' dbpedia-owl:Animal 'di' 'kebun binatang' . =>
      S( (NP 1) (VP 2 (NP 3 4)) (at dbpedia:Zoo) . )

Kamu melihat binatang apa di kebun binatang?

    noun verb 'binatang' 'apa' 'di' 'kebun binatang' ? =>
      S( (NP 1) (VP 2 (NP 3 what=dbpedia-owl:Animal)) (at dbpedia:Zoo) ? )

`what` di sini ditentukan memiliki jenis `dbpedia-owl:Animal`,
untuk membatasi search space jawaban.

Gajah memiliki 4 jumlah kaki.

    Animal 'memiliki' int 'jumlah' 'kaki' . =>
      S( (NP 1) (VP has (NP 4 feet)) .)

Gajah suaranya "auuuk..."

Gajah memiliki hidung panjang yang sering disebut belalai.

Hewan di samping namanya ular.

Tubuhnya panjang dan tidak memiliki kaki dan tangan.

Ular memiliki racun yang sering disebut bisa.

Warna ular disamping adalah hijau.

Kakak menunggangi hewan yang bernama kuda.

Kuda suaranya "yihheeekk".

Kuda suka mengangkut andong / bendi.

Kuda suka makan rumput.

Tubuh Nelly berwarna oranye/jingga/oren/kuning yang indah.

Nelly memiliki kuku/cakar yang runcing/tajam untuk mencakar mangsa.

Nelly suka makan ikan asin.

Hewan di samping namanya adalah kucing.

Cuicit adalah burung pipit Kesayangan Icha

Warnanya kuning dan oranye.

Cuicit suka berkicau/bernyanyi/bersuara di pagi hari.

Suara nya cit cit cit / cuit cuit cuit / merdu. :)

== References

1. [Lexical Resources & NLP Tools Bahasa Indonesia - Universitas Indonesia](http://bahasa.cs.ui.ac.id/resources.php)
2. [Membangun Tree Parse untuk Parsing di Stanford Parser Menggunakan Java - Yuita Arum Sari](http://arumsha.wordpress.com/2012/12/15/membangun-tree-parse-untuk-parsing-di-stanford-parser-menggunakan-java/)

=== Lexical resources

1. [Indonesian WordNet](http://bahasa.cs.ui.ac.id/iwn)
2. [Indonesian Dictionary (Kamus Besar Bahasa Indonesia)](http://bahasa.cs.ui.ac.id/kbbi)

=== NLP tools

1. Porter stemmer for Indonesian
2. [Symbolic Parser](http://bahasa.cs.ui.ac.id/tools/SymbolicParser.zip) -- Bahasa Indonesia Symbolic Parser is a parser is a tool that will create a parse tree structures for Indonesian sentences. Developed by defining Context-Free Grammar (CFG) Rules for Bahasa Indonesia grammar, complete with a simple lexicon of words in Bahasa Indonesia, and run on PCPATR application, available at "http://www.sil.org/pcpatr/".
3. Statistical parser
4. Named entity tagger
5. [Semantic Analyzer](http://bahasa.cs.ui.ac.id/tools/SemanticAnalyzer.zip) -- Bahasa Indonesia Semantic Analyzer is a tool that will create a semantic representation of Bahasa Indonesia sentences in first order predicate logic form. This Semantic Analyzer uses Syntax-Driven Semantic Analysis approach and developed using Indonesian Grammar (Symbolic Parser) that has been translated into PROLOG source. It runs in SWI-PROLOG application available at "http://www.swi-prolog.org/".
6. Semantic Analyzer with Axioms
7. [Morphological Analyzer](http://bahasa.cs.ui.ac.id/tools/MorphologicalAnalyzerIndonesia.zip) -- Morphological Analyzer is a words recognition tools that split word into one or more morphems and also make the corresponding morphological analysis.
