# tdbquery --loc=$HOME/tmp/wn31 --file ~/git/relex-id/core/me.sparql
PREFIX rdf:					<http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:				<http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl:					<http://www.w3.org/2002/07/owl#>
PREFIX lemon:				<http://lemon-model.net/lemon#> 
PREFIX wn31:				<http://wordnet-rdf.princeton.edu/wn31/> 
PREFIX wordnet-ontology:	<http://wordnet-rdf.princeton.edu/ontology#>
PREFIX wn20:				<http://www.w3.org/2006/03/wn/wn20/instances/>
PREFIX uby:					<http://lemon-model.net/lexica/uby/wn/>


select * where {
 ?s ?p ?o .
 FILTER ( ?s IN (wn31:109092497-n, wn31:109115069-n, wn31:Me.-n, wn31:me-n) )
}
