<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="core" nsURI="http://relexid/1.0" nsPrefix="relexid">
  <eClassifiers xsi:type="ecore:EClass" name="Sentence" eSuperTypes="#//PartContainer">
    <eOperations name="generate" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Generate a readable sentence in the specified locale.&#xA;&#xA;@param The translations of resources in this locale's language/variant. Note that informal dictionaries (i.e. bahasa gaul/alay) is a valid use case. Key is resource URI and value is literal."/>
      </eAnnotations>
      <eParameters name="locale" eType="#//Locale"/>
      <eParameters name="dict">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="literal" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Raw literal sentence without preprocessing."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="relations" lowerBound="1"
        upperBound="-1" eType="#//Relation" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PartOfSpeech" abstract="true" interface="true">
    <eOperations name="generate" lowerBound="1" eType="#//GeneratedLiteral">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Generate a readable {@link GeneratedLiteral} in the specified locale.&#xA;&#xA;@param The translations of resources in this locale's language. Note that informal dictionaries (i.e. bahasa gaul/alay) is a valid use case. Key is resource URI and value is literal."/>
      </eAnnotations>
      <eParameters name="locale" eType="#//Locale"/>
      <eParameters name="dict">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="literal" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Literal part text without preprocessing."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="resource" eType="#//QName">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Semantic resource (if known)."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="word" eType="#//QName">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Exact word resource (if known). Available word namespaces are:&#xA;&#xA;&lt;ul>&#xA;&lt;li>wn30: http://purl.org/vocabularies/princeton/wn30/&lt;/li>&#xA;&lt;li>wn30-msa: http://wn-msa.sourceforge.net/wn30-msa/ from &lt;a href=&quot;http://wn-msa.sourceforge.net/&quot;>WordNet Bahasa&lt;/a>&lt;/li>&#xA;&lt;/ul>"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NounPart" eSuperTypes="#//PartOfSpeech"/>
  <eClassifiers xsi:type="ecore:EClass" name="PronounPart" eSuperTypes="#//PartOfSpeech #//Questionable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="person" eType="#//PronounPerson"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="number" eType="#//PronounNumber"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="case" eType="#//PronounCase"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VerbPart" eSuperTypes="#//PartOfSpeech #//PartContainer"/>
  <eClassifiers xsi:type="ecore:EClass" name="LexRule" eSuperTypes="#//ReplacementContainer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="matchers" upperBound="-1"
        eType="#//LexMatcher" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Patterns to match.&#xA;Each pattern is usually separated by whitespace, but sometimes it's not necessary to distinguish, for example, in &quot;I love you.&quot; there is no separator between &quot;you&quot; and &quot;.&quot;."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PrepositionPart" eSuperTypes="#//PartOfSpeech"/>
  <eClassifiers xsi:type="ecore:EClass" name="ConjunctionPart" eSuperTypes="#//PartOfSpeech">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="any syntactic connector (and)"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InterjectionPart" eSuperTypes="#//PartOfSpeech">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="any emotional greeting (or &quot;exclamation&quot;) (ow)"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LexMatcher" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="PartOfSpeechMatcher" eSuperTypes="#//LexMatcher">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="partOfSpeech" lowerBound="1"
        eType="#//PartOfSpeechType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypedResourceMatcher" eSuperTypes="#//LexMatcher">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Refers to an RDF resource (e.g. {@code dbpedia:Elephant}) of a specific class (e.g. {@code dbpedia-owl:Animal})."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="semanticClass" eType="#//QName"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="QName" instanceClassName="javax.xml.namespace.QName"/>
  <eClassifiers xsi:type="ecore:EClass" name="LiteralMatcher" eSuperTypes="#//LexMatcher">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="literals" lowerBound="1"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Any of the literals will match this element."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="caseSensitive" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClassMatcher" eSuperTypes="#//LexMatcher">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Refers to an RDF class itself (e.g. {@code dbpedia-owl:Animal})."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="semanticClass" eType="#//QName"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PartOfSpeechType">
    <eLiterals name="unknown"/>
    <eLiterals name="noun" value="7"/>
    <eLiterals name="verb" value="1"/>
    <eLiterals name="pronoun" value="2"/>
    <eLiterals name="preposition" value="3"/>
    <eLiterals name="conjunction" value="4"/>
    <eLiterals name="interjection" value="5"/>
    <eLiterals name="question" value="6"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Questionable" abstract="true" interface="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Pronoun, adverb, or adjective, depending on how it is used. &#xA;&#xA;&quot;What is that?&quot; -- pronoun &#xA;&quot;What does it matter?&quot; -- adverb &#xA;&quot;What book did you read?&quot; -- adjective&#xA;&#xA;Source:&#xA;http://www.merriam-webster.com/dictionary/what&#xA;&#xA;https://answers.yahoo.com/question/index?qid=20090106144231AApUFKo"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="questioning" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Pronoun, adverb, or adjective, depending on how it is used. &#xA;&#xA;&quot;What is that?&quot; -- pronoun &#xA;&quot;What does it matter?&quot; -- adverb &#xA;&quot;What book did you read?&quot; -- adjective&#xA;&#xA;Source:&#xA;http://www.merriam-webster.com/dictionary/what&#xA;&#xA;https://answers.yahoo.com/question/index?qid=20090106144231AApUFKo"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LexReplacement" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="partOfSpeech" eType="#//PartOfSpeechType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LiteralReplacement" eSuperTypes="#//LexReplacement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="literal" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PunctuationPart" eSuperTypes="#//PartOfSpeech">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="punctuation" lowerBound="1"
        eType="#//Punctuation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PunctuationReplacement" eSuperTypes="#//LexReplacement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="punctuation" eType="#//Punctuation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ResourceReplacement" eSuperTypes="#//LexReplacement #//ReplacementContainer">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Replaces with a semantic resource."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="resource" eType="#//QName">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Semantic resource, which is optional only if the pattern is from {@link ResourceElement} or {@link TypedResourceElement} and {@link #captureGroup} is set, otherwise required."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="captureGroup" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="To get the resource {@link QName} from {@link ResourceElement}, put the pattern capture group number here (note: like regex, first group is 1) and leave {@link #resource} attribute null."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Punctuation">
    <eLiterals name="full_stop"/>
    <eLiterals name="exclamation" value="2"/>
    <eLiterals name="question" value="1"/>
    <eLiterals name="comma" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="QuestionReplacement" eSuperTypes="#//LexReplacement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="question" lowerBound="1"
        eType="#//Question"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Question">
    <eLiterals name="what"/>
    <eLiterals name="who" value="1"/>
    <eLiterals name="when" value="2"/>
    <eLiterals name="where" value="3"/>
    <eLiterals name="how" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AdverbPart" eSuperTypes="#//PartOfSpeech #//Questionable"/>
  <eClassifiers xsi:type="ecore:EClass" name="AdjectivePart" eSuperTypes="#//PartOfSpeech #//Questionable"/>
  <eClassifiers xsi:type="ecore:EEnum" name="PronounPerson">
    <eLiterals name="first"/>
    <eLiterals name="second" value="1"/>
    <eLiterals name="third" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PronounNumber">
    <eLiterals name="singular"/>
    <eLiterals name="plural" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PronounCase">
    <eLiterals name="subject"/>
    <eLiterals name="object" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PartContainer" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parts" upperBound="-1"
        eType="#//PartOfSpeech" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Locale" instanceClassName="java.util.Locale"/>
  <eClassifiers xsi:type="ecore:EClass" name="GeneratedLiteral">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="literal" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="preSeparated" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Whether it needs to be separated from the previous literal by whitespace. All part of speeches require this, except {@link PunctuationPart}."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LexRules">
    <eStructuralFeatures xsi:type="ecore:EReference" name="rules" upperBound="-1"
        eType="#//LexRule" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ResourceMatcher" eSuperTypes="#//LexMatcher">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="resource" lowerBound="1"
        eType="#//QName">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="QName or URI of the resource to match."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PronounReplacement" eSuperTypes="#//LexReplacement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="person" lowerBound="1"
        eType="#//PronounPerson"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="number" lowerBound="1"
        eType="#//PronounNumber"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="case" lowerBound="1" eType="#//PronounCase"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UnrecognizedPart" eSuperTypes="#//PartOfSpeech">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A part that's yet to be recognized. At the start of the parsing, all tokens first become UnrecognizedPart."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReplacementContainer" abstract="true"
      interface="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="replacements" upperBound="-1"
        eType="#//LexReplacement" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Replacements to be made when the patterns match.&#xA;Note that LexRules can be repeated for multiple iterations."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SubjectRelation" eSuperTypes="#//Relation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="subject" lowerBound="1"
        eType="#//PartOfSpeech">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Can be either {@link NounPart} or {@link PronounPart}."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="verb" lowerBound="1" eType="#//VerbPart"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ObjectRelation" eSuperTypes="#//Relation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="verb" lowerBound="1" eType="#//VerbPart"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="object" lowerBound="1"
        eType="#//PartOfSpeech">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Can be either {@link NounPart} or {@link PronounPart}."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Relation" abstract="true" interface="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Provides relationship information between part of speeches."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RelationRule">
    <eStructuralFeatures xsi:type="ecore:EReference" name="matchers" upperBound="-1"
        eType="#//PartMatcher" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="relationDefs" upperBound="-1"
        eType="#//RelationDef" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RelationRules">
    <eStructuralFeatures xsi:type="ecore:EReference" name="rules" upperBound="-1"
        eType="#//RelationRule" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypedPartMatcher" eSuperTypes="#//PartMatcher">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Matches a particular subclass of {@link PartOfSpeech}."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="partOfSpeech" eType="#//PartOfSpeechType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PartMatcher" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="matchers" upperBound="-1"
        eType="#//PartMatcher" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Child matchers of this {@link PartMatcher}. Note that a parent PartMatcher may only match if all its children have matched."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SubjectRelationDef" eSuperTypes="#//RelationDef">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Defines a {@link SubjectRelation}."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="verb" lowerBound="1" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="subject" lowerBound="1"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RelationDef" abstract="true" interface="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Defines a {@link Relation}.&#xA;&#xA;&lt;p>Since {@link PartMatcher} is hierarchical, binding paths are hierarchical also with format: &quot;{parent}/{child}/{grandchild}...&quot;&#xA;(in XMI it's {@code int array}).&#xA;Note that as in regex, binding numbers are 1-based.&#xA;e.g. &quot;3/1&quot; refer to: first children of third root matcher."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ObjectRelationDef" eSuperTypes="#//RelationDef">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Defines an {@link ObjectRelation}."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="verb" lowerBound="1" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="object" lowerBound="1"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
</ecore:EPackage>
